### ISSUE TITLE
Add a file exists check to prevent crash

### ISSUE THREAD

**Issue by d-karstens** [dodecastudio/craft-blurhash#8]
Hi,

Loving the plugin, but I was wondering if it would it be possible to add a file exists check to BlurHash functions to prevent errors like the following if a file doesn't exist locally?

![Screen Shot 2022-04-13 at 2 04 32 pm](https://user-images.githubusercontent.com/21274925/163100979-77a5aa4b-b9ff-4cd4-a40b-63f95a6cdc1b.png)

We want to use BlurHash along with [Untransform](https://github.com/putyourlightson/craft-untransform) so we can use images from our staging site instead of having to download them all the time

Thanks!

**Comment by tomkiss** [comment]
Hi @mokopan,

Please can you share a bit of info about your setup here so I can try to repro what you're seeing?

Craft version, some template markup and information about your asset buckets would handy.

Thanks 😊

**Comment by d-karstens** [comment]
Sure!

We're running Craft version 3.7.38 just using a simple Nitro setup

Our assets volumes are set up as follows, with `@webroot` set to `/app/web`
![Screen Shot 2022-04-13 at 3 37 08 pm](https://user-images.githubusercontent.com/21274925/163111114-8ff813fa-ba0e-4de1-9727-a2a0129cf25a.png)

And then our images are just a simple lazyload macro as follows
```
<img class="lazyload"
        decoding="async"
        data-sizes="auto"
        data-src="{{ image.getUrl() }}"
        data-lowsrc="{{ blurhash(image) }}"
/>
```

With the Untransform plugin the image base url points to our staging site which works, but I'm guessing because the blurhash function is still looking for the image locally and it isn't there it throws an error 

Hopefully this helps/makes sense!

**Comment by tomkiss** [comment]
Great, thank you - I'll take a look when I get a mo 🙂

**Comment by tomkiss** [comment]
Hey @mokopan. I just pushed out [1.2.3](https://github.com/dodecastudio/craft-blurhash/releases/tag/v1.2.3) which should fix this issue. But, let me know if you find any problems!

**Comment by d-karstens** [comment]
Hey @tomkiss, thanks for checking that out!

Unfortunately the same error is still happening 😔 

I tried to have a look myself and reckon it it _could_ be this line  https://github.com/dodecastudio/craft-blurhash/blob/main/src/services/BlurHashService.php#L85
Seems like the fileExists function wants a path so I changed it (and line 90) to `!$asset->getVolume()->fileExists($asset->getPath()` and it looks like it works

I'm pretty novice with PHP though so not certain 😅

**Comment by tomkiss** [comment]
Oh dear, sorry about that! I somehow checked in some reverted/unfinished code. Should be fixed in 1.2.4 now.

**Comment by d-karstens** [comment]
Thanks, works perfect now!

Planted a couple trees ☺️
